FILES = {}

FILES["src/erisml/interop/pddl_adapter.py"] = [
"from __future__ import annotations\n",
"\n",
"from erisml.core.model import ErisModel\n",
"\n",
"try:\n",
"    import tarski\n",
"    from tarski import fstrips as fs\n",
"except ImportError:  # pragma: no cover\n",
"    tarski = None\n",
"    fs = None\n",
"\n",
"\n",
"def erisml_to_tarski(model: ErisModel):\n",
"    \"\"\"Convert ErisML model to Tarski FSTRIPS problem (stub).\"\"\"\n",
"    if tarski is None or fs is None:\n",
"        raise ImportError(\n",
"            \"tarski not installed. Install via `pip install tarski`.\"\n",
"        )\n",
"\n",
"    lang = fs.language.FStripsLanguage(\"erisml\")\n",
"\n",
"    obj_sorts = {}\n",
"    for name, obj_type in model.env.object_types.items():\n",
"        sort = lang.sort(name)\n",
"        obj_sorts[name] = sort\n",
"        for inst in obj_type.instances:\n",
"            lang.constant(inst, sort)\n",
"\n",
"    problem = fs.Problem(lang)\n",
"    return problem\n",
]

FILES["src/erisml/interop/pettingzoo_adapter.py"] = [
"from __future__ import annotations\n",
"\n",
"from typing import Any, Dict\n",
"\n",
"from gymnasium import spaces\n",
"from pettingzoo.utils import AECEnv\n",
"\n",
"from erisml.core.engine import ErisEngine\n",
"from erisml.core.model import ErisModel\n",
"from erisml.core.types import ActionInstance\n",
"\n",
"\n",
"class ErisPettingZooEnv(AECEnv):\n",
"    \"\"\"Minimal PettingZoo adapter. Customize for real domains.\"\"\"\n",
"\n",
"    metadata = {\"render_modes\": [\"human\"]}\n",
"\n",
"    def __init__(self, model: ErisModel):\n",
"        super().__init__()\n",
"        self.model = model\n",
"        self.engine = ErisEngine(model)\n",
"        self.possible_agents = list(model.agents.keys())\n",
"        self.agents = self.possible_agents[:]\n",
"        self._agent_index = 0\n",
"        self._state: Dict[str, Any] = {}\n",
"        self._cumulative_rewards = {a: 0.0 for a in self.agents}\n",
"\n",
"        self.action_spaces = {a: spaces.Discrete(4) for a in self.agents}\n",
"        self.observation_spaces = {a: spaces.Dict({}) for a in self.agents}\n",
"\n",
"    def reset(self, seed=None, options=None):\n",
"        self.agents = self.possible_agents[:]\n",
"        self._agent_index = 0\n",
"        self._state = {}\n",
"        self._cumulative_rewards = {a: 0.0 for a in self.agents}\n",
"\n",
"    def observe(self, agent: str):\n",
"        return {}\n",
"\n",
"    def step(self, action):\n",
"        if not self.agents:\n",
"            return\n",
"        agent = self.agents[self._agent_index]\n",
"        act = self._decode_action(agent, action)\n",
"        try:\n",
"            self._state = self.engine.step(self._state, act)\n",
"        except Exception as exc:  # pragma: no cover\n",
"            print(f\"Engine error: {exc}\")\n",
"        self._agent_index = (self._agent_index + 1) % len(self.agents)\n",
"\n",
"    def _decode_action(self, agent: str, action: int) -> ActionInstance:\n",
"        return ActionInstance(agent=agent, name=\"noop\", params={})\n",
"\n",
"    def render(self):\n",
"        print(\"State:\", self._state)\n",
"\n",
"    def close(self):\n",
"        pass\n",
]

FILES["src/erisml/examples/tiny_home.py"] = [
"from __future__ import annotations\n",
"\n",
"from typing import Any, Dict\n",
"\n",
"from erisml.core.engine import ErisEngine\n",
"from erisml.core.model import AgentModel, EnvironmentModel, ErisModel\n",
"from erisml.core.norms import NormRule, NormSystem, NormViolation\n",
"from erisml.core.types import (\n",
"    ActionInstance,\n",
"    ActionSchema,\n",
"    BaseType,\n",
"    EnvironmentRule,\n",
"    StateVarDomain,\n",
")\n",
"\n",
"\n",
"def build_tiny_home_model() -> ErisModel:\n",
"    env = EnvironmentModel(name=\"TinyHome\")\n",
"    env.add_object_type(\"Room\", [\"r1\", \"r2\"])\n",
"\n",
"    env.add_state_var(\"location_human\", StateVarDomain(BaseType.STR))\n",
"    env.add_state_var(\"location_robot\", StateVarDomain(BaseType.STR))\n",
"    env.add_state_var(\"light_on_r1\", StateVarDomain(BaseType.BOOL))\n",
"    env.add_state_var(\"light_on_r2\", StateVarDomain(BaseType.BOOL))\n",
"\n",
"    def move_robot_rule(state: Dict[str, Any], params: Dict[str, Any]) -> Dict[str, Any]:\n",
"        from_room = params[\"from\"]\n",
"        to_room = params[\"to\"]\n",
"        new_state = dict(state)\n",
"        if state[\"location_robot\"] == from_room:\n",
"            new_state[\"location_robot\"] = to_room\n",
"        return new_state\n",
"\n",
"    def toggle_light_rule(state: Dict[str, Any], params: Dict[str, Any]) -> Dict[str, Any]:\n",
"        room = params[\"room\"]\n",
"        new_state = dict(state)\n",
"        key = f\"light_on_{room}\"\n",
"        new_state[key] = not state[key]\n",
"        return new_state\n",
"\n",
"    env.add_rule(EnvironmentRule(\"move_robot\", [\"from\", \"to\"], move_robot_rule))\n",
"    env.add_rule(EnvironmentRule(\"toggle_light\", [\"room\"], toggle_light_rule))\n",
"\n",
"    robot = AgentModel(name=\"Robot\")\n",
"    robot.add_capability(ActionSchema(\"move_robot\", [\"from\", \"to\"]))\n",
"    robot.add_capability(ActionSchema(\"toggle_light\", [\"room\"]))\n",
"\n",
"    agents = {\"Robot\": robot}\n",
"\n",
"    norms = NormSystem(name=\"Safety\")\n",
"\n",
"    def prohibition_move_to_r2(state: Dict[str, Any], action: ActionInstance) -> bool:\n",
"        return (\n",
"            action.agent == \"Robot\"\n",
"            and action.name == \"move_robot\"\n",
"            and action.params.get(\"to\") == \"r2\"\n",
"        )\n",
"\n",
"    norms.add_rule(\n",
"        NormRule(\"no_move_into_r2\", \"prohibition\", prohibition_move_to_r2)\n",
"    )\n",
"\n",
"    def obligation_light_on_human_room(state: Dict[str, Any], action: ActionInstance) -> bool:\n",
"        room = state[\"location_human\"]\n",
"        key = f\"light_on_{room}\"\n",
"        return not state[key]\n",
"\n",
"    norms.add_rule(\n",
"        NormRule(\n",
"            \"keep_human_room_lit\", \"obligation\", obligation_light_on_human_room\n",
"        )\n",
"    )\n",
"\n",
"    model = ErisModel(env=env, agents=agents, norms=norms)\n",
"    return model\n",
"\n",
"\n",
"def demo_tiny_home_run() -> None:\n",
"    model = build_tiny_home_model()\n",
"    engine = ErisEngine(model)\n",
"\n",
"    state: Dict[str, Any] = {\n",
"        \"location_human\": \"r1\",\n",
"        \"location_robot\": \"r1\",\n",
"        \"light_on_r1\": False,\n",
"        \"light_on_r2\": False,\n",
"    }\n",
"\n",
"    print(\"Initial state:\", state)\n",
"\n",
"    a1 = ActionInstance(agent=\"Robot\", name=\"toggle_light\", params={\"room\": \"r1\"})\n",
"    state = engine.step(state, a1)\n",
"    print(\"After toggle_light(r1):\", state)\n",
"\n",
"    a2 = ActionInstance(agent=\"Robot\", name=\"move_robot\", params={\"from\": \"r1\", \"to\": \"r2\"})\n",
"    try:\n",
"        engine.step(state, a2)\n",
"    except NormViolation as exc:\n",
"        print(\"Blocked action:\", a2)\n",
"        print(\"Reason:\", exc)\n",
"\n",
"    print(\"Final state:\", state)\n",
"    print(\"Metrics: steps =\", engine.metrics.steps, \"NVR =\", engine.metrics.nvr)\n",
"\n",
"\n",
"if __name__ == \"__main__\":\n",
"    demo_tiny_home_run()\n",
]
