"""Chapter 22: Geometric Jurisprudence — full content tuples."""

CH22_JURISPRUDENCE = [
    ('Heading 1', 'Chapter 22: Geometric Jurisprudence — Algorithmic Justice and Legal Manifolds'),
    ('Body Text', 'This chapter applies the Geometric Ethics framework to legal reasoning and algorithmic justice. The central thesis is that law — the operating system of civilization — has an implicit mathematical structure that natural language obscures but geometry makes explicit. Legal reasoning is pathfinding on a directed simplicial complex (the judicial complex), constitutional review is a topological computation (path homology preservation), Hohfeldian jural relations form a gauge group (the octahedral group D_4 x| D_4), and conservation laws characterize valid legal transformations. The framework formalizes what the legal system already demands — equal treatment, procedural regularity, constitutional conformity — and makes those demands computationally checkable.'),
    ('Body Text', ''),
    ('Heading 2', '22.1 Law as Geometric Structure'),
    ('Body Text', 'Legal reasoning has resisted formalization for centuries. Hart\'s positivism, Dworkin\'s interpretivism, and the law-and-economics movement each capture aspects of legal structure but none provides a complete mathematical framework. The geometric approach identifies the source of this difficulty: law operates on a multi-dimensional space (not a scalar), the space is directed (precedent flows forward in time and downward in hierarchy), and the space has topological structure (constitutional constraints are not metric but topological — they concern which paths exist, not how long they are).'),
    ('Body Text', 'The law-and-economics movement attempted scalar reduction: legal outcomes should maximize economic efficiency. This is the legal analog of Homo economicus — and it fails for the same reason. The Scalar Irrecoverability Theorem (Chapter 15) applies: no continuous function from the legal decision space to a scalar can be injective. Legal decisions that are "efficient" may be unjust, autonomy-violating, or trust-destroying. The scalar projection loses the information needed to evaluate these dimensions.'),
    ('Body Text', ''),
    ('Heading 2', '22.2 The Judicial Complex'),
    ('Body Text', 'Definition 22.1 (Judicial Complex). The judicial complex K is a weighted, directed simplicial complex with the following structure:'),
    ('Body Text', 'Vertices (0-simplices): Each decided case c_i carries an attribute vector v(c_i) in R^8 encoding eight legal dimensions, court level metadata l(c_i) in {trial, appellate, supreme}, and decision date tau(c_i).'),
    ('Body Text', 'Directed edges (1-simplices): c_i -> c_j exists when case c_j cites case c_i. This encodes temporal precedence (tau(c_i) < tau(c_j): cases cannot cite future decisions) and hierarchical authority (binding precedent has low edge cost; persuasive authority has high cost).'),
    ('Body Text', 'Higher simplices (k-simplices): A k-simplex exists when cases form a doctrinal cluster — a set of mutually citing cases that collectively establish a legal doctrine.'),
    ('Body Text', 'The eight legal dimensions are:'),
    ('Body Text', 'd_1: Entitlement structure — the configuration of Hohfeldian positions (rights, duties, liberties, no-rights, powers, immunities, liabilities, disabilities).'),
    ('Body Text', 'd_2: Factual nexus — causal, evidentiary, and material connections between parties and events.'),
    ('Body Text', 'd_3: Procedural posture — standing, jurisdiction, timeliness, exhaustion of administrative remedies.'),
    ('Body Text', 'd_4: Statutory authority — the legislative basis and statutory framework governing the dispute.'),
    ('Body Text', 'd_5: Constitutional conformity — respect for fundamental rights, structural provisions, separation of powers.'),
    ('Body Text', 'd_6: Precedential constraint — the weight of stare decisis, binding versus persuasive authority.'),
    ('Body Text', 'd_7: Remedial scope — available relief (compensatory damages, injunctive relief, specific performance, declaratory judgment).'),
    ('Body Text', 'd_8: Public interest — societal implications, third-party effects, regulatory impact.'),
    ('Body Text', 'Remark. The legal complex uses eight dimensions rather than the moral manifold\'s nine because the Hohfeldian entitlement structure (d_1) subsumes some moral dimensions that are separately tracked in the ethical context. The framework\'s validity does not depend on this specific count; the theorems hold for any finite-dimensional complex.'),
    ('Body Text', 'Definition 22.2 (Legal Edge Weights). The weight of a directed edge c_i -> c_j in K is:'),
    ('Body Text', '    w(c_i -> c_j) = Dv^T Sigma^{-1} Dv  +  beta * 1[regime boundary crossed]  +  h(l(c_i), l(c_j))'),
    ('Body Text', 'where Dv = v(c_j) - v(c_i), Sigma is the 8x8 legal-dimensional covariance matrix, beta is the regime-boundary penalty, and h(l_i, l_j) is the hierarchical cost: 0 if l_i > l_j (binding: higher to lower court), eta (persuasive penalty) if same level, and infinity if reverse hierarchical direction (lower courts cannot overrule higher courts).'),
    ('Body Text', ''),
    ('Heading 2', '22.3 Legal Invariance Principles'),
    ('Body Text', 'Definition 22.3 (Legal Invariance Principle, LIP). A legal judgment procedure J_law is epistemically well-posed if and only if:'),
    ('Body Text', '    J_law(tau(x)) = J_law(x)    for all tau in T_irrelevant'),
    ('Body Text', 'where T_irrelevant includes: renaming parties, changing protected-class attributes (race, gender, religion, national origin), rephrasing legal arguments without changing logical content, changing order of evidence presentation, and translating between languages. The LIP formalizes what the Equal Protection Clause, Due Process Clause, and Rule of Law already demand in prose.'),
    ('Body Text', 'Definition 22.4 (Judicial Bond Invariance Principle, JBIP). Legal evaluation must be invariant under transformations preserving Hohfeldian bond structure:'),
    ('Body Text', '    J_law(tau(x)) = J_law(x)    for all tau in T_bond-preserving'),
    ('Body Text', 'The JBIP is stronger than the LIP: it specifies the mathematical structure (Hohfeldian relations) whose preservation defines legal equivalence.'),
    ('Body Text', 'Definition 22.5 (Legal Bond Index). The Legal Bond Index is:'),
    ('Body Text', '    LBI = (1/|S|) Sum_{s in S} ||J_law(tau(s)) - J_law(s)||'),
    ('Body Text', 'where S is a test set of cases and tau ranges over bond-preserving transformations. LBI is computable from existing case databases and provides a quantitative measure of judicial consistency.'),
    ('Body Text', ''),
    ('Heading 2', '22.4 The Hohfeldian Octad and Gauge Theory'),
    ('Body Text', 'The Hohfeldian system of jural relations — developed by Wesley Hohfeld in 1913 and discussed in Chapter 3 — consists of eight fundamental positions organized in two squares:'),
    ('Body Text', 'First square (first-order relations): Right <-> Duty (correlatives), Liberty <-> No-right (correlatives), Right <-> No-right (opposites), Liberty <-> Duty (opposites).'),
    ('Body Text', 'Second square (second-order relations, governing legal change): Power <-> Liability (correlatives), Immunity <-> Disability (correlatives), Power <-> Disability (opposites), Immunity <-> Liability (opposites).'),
    ('Body Text', 'Theorem 22.1 (Octahedral Gauge Group). The symmetry group of the full Hohfeldian octad is the semi-direct product:'),
    ('Body Text', '    G_Ho = D_4 x|_phi D_4'),
    ('Body Text', 'where the first D_4 acts on first-order relations (right-duty-liberty-no-right), the second D_4 acts on second-order relations (power-liability-immunity-disability), and the homomorphism phi: D_4 -> Aut(D_4) encodes how second-order operations act on first-order positions.'),
    ('Body Text', 'Proof. Each Hohfeldian square admits D_4 symmetry: two correlative pairs generate the dihedral group of the square (two reflections plus rotations). However, the squares are not independent — second-order positions (powers, immunities) actively transform first-order positions (creating and destroying rights and duties). This asymmetric coupling is precisely the structure of a semi-direct product. The multiplication rule (g_1, g_2) * (h_1, h_2) = (g_1 * phi(g_2)(h_1), g_2 * h_2) encodes that the first-order transformation h_1 is "twisted" by the second-order transformation g_2. []'),
    ('Body Text', 'Remark. In the parent framework (Chapter 12), the gauge group was D_4 acting on the first four Hohfeldian positions. Law requires the full octad — both first-order relations (which govern static legal positions) and second-order relations (which govern legal change). The extension from D_4 to D_4 x| D_4 is the mathematical content of the distinction between static and dynamic legal structure.'),
    ('Body Text', 'Definition 22.6 (Legal Wilson Loop). A legal Wilson loop is the holonomy around a closed path in the judicial complex:'),
    ('Body Text', '    W(gamma) = P exp(integral_gamma A_mu dx^mu)'),
    ('Body Text', 'where A_mu is the legal connection encoding how Hohfeldian positions change under parallel transport through case law.'),
    ('Body Text', 'Proposition 22.1 (Wilson Loop Test for Consistency). A body of case law is internally consistent if and only if all Wilson loops are trivial. Non-trivial Wilson loops identify specific circuits of legal reasoning that produce contradictions — "bugs" in the legal system that are detectable algorithmically rather than waiting for a case to expose them.'),
    ('Body Text', ''),
    ('Heading 2', '22.5 Topological Constitutionality'),
    ('Body Text', 'Constitutional review — determining whether a statute is constitutional — is the most consequential legal computation. The geometric framework recasts it as a topological problem.'),
    ('Body Text', 'Definition 22.7 (Constitutional Subcomplex). The constitutional subcomplex C is a subcomplex of K consisting of all simplices satisfying constitutional constraints:'),
    ('Body Text', '    C = {sigma in K | Phi_k(sigma) = true, k = 1, ..., K}'),
    ('Body Text', 'where the Boolean predicates Phi_k encode constitutional provisions: Phi_EP for Equal Protection invariance, Phi_DP for Due Process well-definedness, Phi_1A for First Amendment protection, Phi_SoP for Separation of Powers.'),
    ('Body Text', 'Because K is a directed complex (edges encode temporal and hierarchical order), the appropriate homology theory is path homology (Grigor\'yan-Lin-Muranov-Yau), not standard simplicial homology. An elementary p-path is a sequence of vertices (c_{i_0}, ..., c_{i_p}) connected by directed edges. The path homology groups are:'),
    ('Body Text', '    H_n^path(K; Z) = ker partial_n / im partial_{n+1}'),
    ('Body Text', 'Theorem 22.2 (Topological Constitutionality). A statute ell is constitutional if and only if it preserves the path homology of the constitutional subcomplex:'),
    ('Body Text', '    H_n^path(C; Z) = H_n^path(C_ell; Z)    for all n >= 0'),
    ('Body Text', 'Equivalently: ell is constitutional if and only if it does not create new non-trivial directed cycles in C.'),
    ('Body Text', 'Proof. A non-trivial directed cycle in C_ell that does not exist in C represents a directed sequence of legal reasoning that returns to the starting vertex with altered Hohfeldian structure — a legal contradiction. Since the cycle is directed, each step respects temporal and hierarchical order, making it a genuine inconsistency rather than an artifact of undirected analysis. Preservation of path homology prevents such contradictions. Conversely, if a new non-trivial cycle exists, a sequence of valid legal steps creates a contradiction, and the statute that enabled the cycle is the source. []'),
    ('Body Text', 'This theorem converts constitutional review from a semantic dispute ("what does equal protection mean?") into a topological calculation on a finite directed graph. The computation is finite: path homology groups are finitely generated abelian groups computable via Smith normal form on the directed path complex.'),
    ('Body Text', ''),
    ('Heading 2', '22.6 Conservation Laws in Legal Systems'),
    ('Body Text', 'Theorem 22.3 (Liability-Damages Conservation). In a closed bilateral dispute between plaintiff A and defendant B within a fixed legal framework F:'),
    ('Body Text', '    L(A) + L(B) = 0'),
    ('Body Text', 'where L(X) is the net liability of party X. Every dollar of damages to A imposes exactly one dollar of liability on B. Every right created for A imposes a correlative duty on B.'),
    ('Body Text', 'Proof. By Hohfeldian correlative structure: (1) every right of A is a correlative duty of B; (2) every liability of B is a correlative power of A; (3) adjudication recognizes or assigns positions within the fixed framework F — it does not create positions ex nihilo. Therefore, at every step, Delta E(A) + Delta E(B) = 0. []'),
    ('Body Text', 'Remark (Conservation Breaking). Three operations break liability-damages conservation: (a) Legislation — creates causes of action ex nihilo (symmetry-breaking analogous to gauge symmetry breaking in physics); (b) Constitutional amendment — alters the topological constraint space C; (c) Third-party intervention — adding a new party breaks closure (conservation is restored by extending the system to include all parties).'),
    ('Body Text', 'Theorem 22.4 (Equal Protection as Gauge Symmetry). Equal Protection (14th Amendment) requires that legal evaluation be invariant under protected-class transformations. In any closed bilateral dispute, this invariance implies entitlement balance: the signed sum of Hohfeldian positions is invariant under adjudication.'),
    ('Body Text', 'Theorem 22.5 (Due Process as Well-Definedness). Due Process requires that J_law be well-defined on the quotient space K / T_irrelevant. Failure to factor through the quotient means legal outcomes depend on representation (the specific description of the case) rather than substance (the equivalence class under legally irrelevant transformations). This is the formal content of procedural due process.'),
    ('Body Text', ''),
    ('Heading 2', '22.7 Legal Disputes as A* Pathfinding'),
    ('Body Text', 'A legal dispute is pathfinding on K. The plaintiff starts at vertex c_0 (current legal position) and seeks a path to a goal region G (vertices where similarly situated plaintiffs prevailed). The path gamma represents the chain of doctrinal steps through case law — the legal argument.'),
    ('Body Text', 'Definition 22.8 (Legal Friction). The legal friction of a path gamma is:'),
    ('Body Text', '    BF_law(gamma) = Sum w(c_i, c_{i+1})  +  Sum_k beta_k * 1[crosses regime k]  +  Sum_j omega_j * delta_j(gamma)'),
    ('Body Text', 'with three components: (1) argument complexity — total edge weight, measuring doctrinal distance; (2) boundary penalties — cost of crossing jurisdictional, statutory, or constitutional regime boundaries; (3) burden of proof — cost of establishing facts, with omega_j weighting evidentiary requirements.'),
    ('Body Text', 'Theorem 22.6 (Optimal Legal Argument). The optimal legal argument is the minimum-cost path:'),
    ('Body Text', '    gamma* = arg min_gamma BF_law(gamma)    subject to gamma(0) = c_0, gamma(end) in G'),
    ('Body Text', 'This is A* search with f(n) = g(n) + h(n), where g(n) is accumulated legal friction from c_0 to n (the argument built so far) and h(n) is the doctrinal heuristic estimating remaining friction to G (legal judgment about remaining burden).'),
    ('Body Text', 'Theorem 22.7 (Admissibility of Doctrinal Heuristics). A doctrinal heuristic h_D is admissible if the doctrine correctly identifies claim elements and assigns non-negative costs not exceeding actual costs. If h_D is admissible, A* search using h_D finds the optimal legal argument.'),
    ('Body Text', 'Examples of doctrinal heuristics: The prima facie case in tort law estimates the cost of establishing duty, breach, causation, and damages — an admissible decomposition of total legal friction. Burden-shifting frameworks (McDonnell Douglas in employment discrimination) provide a three-step heuristic for evaluating discrimination claims. Strict scrutiny assigns high estimated cost to the government\'s path and low cost to the challenger\'s. Stare decisis is a pattern database of pre-computed optimal paths: precedents provide near-optimal heuristics for similar cases.'),
    ('Body Text', 'Adversarial Pathfinding. Litigation is a two-player game. The plaintiff minimizes friction to G_plaintiff; the defendant either blocks the path, increases plaintiff\'s friction above the burden threshold, or establishes a shorter path to G_defendant (dismissal). The minimax value V(c_0) = min_{gamma_d} max_{gamma_p} [BF_law(gamma_d) - BF_law(gamma_p)] determines the outcome: V(c_0) > 0 implies plaintiff prevails; V(c_0) <= 0 implies defendant prevails.'),
    ('Body Text', 'Settlement as Shortcut. A settlement is a vertex c_s both parties prefer to the expected litigation outcome. A non-empty settlement region exists when the combined litigation costs exceed the distance between the parties\' goal regions. This explains why most disputes settle: path lengths through case law nearly always exceed the distance between the parties\' positions.'),
    ('Body Text', ''),
    ('Heading 2', '22.8 Precedent as Weight Deformation'),
    ('Body Text', 'A binding precedent P at vertex c_P with holding H_P modifies edge weights throughout its neighborhood:'),
    ('Body Text', '    w(c_i -> c_j) -> w(c_i -> c_j) + Dw(c_i -> c_j; P)'),
    ('Body Text', 'The deformation concentrates near c_P and decays with graph distance: |Dw| ~ w_P / d(c_i, c_P)^n, where w_P is precedential weight (Supreme Court > Circuit > District).'),
    ('Body Text', 'Overruling as Phase Transition. Overruling precedent P by P\' is graph surgery:'),
    ('Body Text', '    w(c_i -> c_j) -> w(c_i -> c_j) - Dw(c_i -> c_j; P) + Dw(c_i -> c_j; P\')'),
    ('Body Text', 'This is a legal phase transition: the filtration structure changes, vertices cross regime boundaries discontinuously, and the shortest-path structure alters abruptly. Stare decisis creates a cost barrier around precedents — a form of legal inertia. The barrier height equals the accumulated reliance interest (the total weight of subsequent cases decided under the precedent). Courts overrule when the topological benefit (removing constitutional inconsistency, reducing Wilson loop complexity) exceeds the transition cost.'),
    ('Body Text', 'Example 22.1 (Brown v. Board of Education). Overruling Plessy v. Ferguson (1896) by Brown v. Board (1954) is a phase transition in the equal-protection region of K. Under Plessy, "separate but equal" vertices had finite weight to the constitutional region. Under Brown, those edges acquire infinite weight — segregation itself violates equal protection. Previously "legal" vertices become unreachable by valid constitutional paths. The transition cost was enormous (decades of subsequent litigation), but the topological benefit was a drastic simplification of the equal-protection homology.'),
    ('Body Text', ''),
    ('Heading 2', '22.9 Empirical Calibration Pipeline'),
    ('Body Text', 'The judicial complex K is not merely a theoretical construct — it is empirically constructible from existing legal databases. The calibration pipeline proceeds in five steps:'),
    ('Body Text', 'Step 1 (Embedding): Each judicial opinion t_i is embedded via LaBSE (Language-agnostic BERT Sentence Embedding) into e(t_i) in R^768. The language-invariance of LaBSE ensures that the same legal concept in different languages maps to the same embedding region — critical for cross-jurisdictional analysis.'),
    ('Body Text', 'Step 2 (Dimension Scoring): Eight linear probes f_k: R^768 -> [0,1] (logistic regression classifiers trained on labeled legal texts) produce the attribute vector v(c_i) = (f_1(e), ..., f_8(e)). The predecessor moral probes achieved F_1 = 0.74-0.91; legal probes target the same performance.'),
    ('Body Text', 'Step 3 (Covariance Estimation): From N scored cases, estimate the 8x8 covariance matrix Sigma_hat. This captures cross-dimensional dependencies (statutory authority correlates with remedial scope; procedural posture gates merits access).'),
    ('Body Text', 'Step 4 (Edge-Weight Computation): For each citation c_i -> c_j, compute the Mahalanobis-weighted directed edge cost plus boundary penalties and hierarchical cost.'),
    ('Body Text', 'Step 5 (Outcome Calibration): Fit a regularized logistic model from attribute vectors to case outcomes; the fitted weight matrix provides outcome-calibrated inverse covariance. The effective metric blends corpus-derived and outcome-derived structure: Sigma_eff^{-1} = lambda * Sigma_hat^{-1} + (1-lambda) * W, with lambda set by cross-validation.'),
    ('Body Text', 'Critical property: the pipeline is deterministic. LaBSE weights are frozen; linear probes are logistic regression (no sampling, no temperature). The same input always produces the same vector. This contrasts with LLM-based scoring, where outputs vary across runs. For legal applications, determinism is non-negotiable.'),
    ('Body Text', ''),
    ('Heading 2', '22.10 Falsifiable Predictions'),
    ('Body Text', 'Prediction 1 (Legal Bond Index Correlates): Courts with higher LBI scores (lower invariance under bond-preserving transformations) should have higher reversal rates on appeal. Falsified if: LBI is uncorrelated with reversal rates.'),
    ('Body Text', 'Prediction 2 (Dimensional Factor Structure): Factor analysis of scored judicial opinions should recover approximately eight independent legal dimensions. Falsified if: the factor structure is consistently lower-rank (fewer than six) or higher-rank (more than ten).'),
    ('Body Text', 'Prediction 3 (Precedent Decay): The influence of a precedent on edge weights should decay with graph distance from the precedent vertex, with binding precedent showing slower decay than persuasive authority. Falsified if: precedential influence is distance-invariant.'),
    ('Body Text', 'Prediction 4 (Constitutional Cycle Detection): Non-trivial directed cycles in the constitutional subcomplex should correlate with statutes subsequently struck down by courts. Falsified if: cycle presence is uncorrelated with judicial invalidation.'),
    ('Body Text', 'Prediction 5 (Settlement Region): The existence and size of the settlement region should be predictable from the parties\' graph positions and expected path costs. Falsified if: settlement rates are independent of computed path costs.'),
    ('Body Text', 'Prediction 6 (Cross-Jurisdictional Invariance): The framework\'s structural features (gauge group, conservation laws, topological constitutionality) should hold across legal traditions (common law, civil law, Islamic law, customary law) at the structural level, even as the specific dimensions and metric vary. Falsified if: the framework applies only to common-law systems.'),
    ('Body Text', ''),
    ('Heading 2', '22.11 Connection to the Framework'),
    ('Body Text', 'The Geometric Jurisprudence program extends the parent framework in five directions:'),
    ('Body Text', '1. Chapter 3 introduced Hohfeldian relations as the discrete structure of moral bonds. This chapter elevates them to a gauge group (D_4 x| D_4) and shows that the semi-direct product structure captures the asymmetric coupling between static legal positions and dynamic legal change.'),
    ('Body Text', '2. Chapter 11 established pathfinding as the formal model of moral reasoning. This chapter shows that legal reasoning is adversarial pathfinding — a two-player variant where plaintiff and defendant simultaneously optimize on K, with doctrines serving as domain-specific heuristic functions.'),
    ('Body Text', '3. Chapter 12 established conservation laws from invariance. This chapter derives liability-damages conservation from Hohfeldian correlative structure and shows that conservation-breaking operations (legislation, constitutional amendment, third-party intervention) correspond to gauge symmetry breaking.'),
    ('Body Text', '4. Chapter 15 established scalar irrecoverability. This chapter applies it to the law-and-economics program: scalar efficiency measures (Kaldor-Hicks) lose the seven non-monetary dimensions of the legal decision space.'),
    ('Body Text', '5. The directed nature of the judicial complex (temporal, hierarchical) requires path homology rather than standard simplicial homology — a mathematical upgrade that reflects the irreversibility of legal time and the asymmetry of legal authority.'),
    ('Body Text', ''),
    ('Heading 2', '22.12 Summary'),
    ('Body Text', 'This chapter has shown that the geometric ethics framework, when applied to law, yields:'),
    ('Body Text', '1. The judicial complex K: a directed, weighted simplicial complex constructible from case law databases.'),
    ('Body Text', '2. The octahedral gauge group D_4 x| D_4: the full symmetry of Hohfeldian jural relations, extending the D_4 of the parent framework to include second-order legal change.'),
    ('Body Text', '3. Topological constitutionality: constitutional review as path homology preservation — a finite computation on a directed graph.'),
    ('Body Text', '4. Conservation laws: liability-damages conservation from Hohfeldian correlative structure, with legislation as symmetry breaking.'),
    ('Body Text', '5. Legal disputes as adversarial A* pathfinding, with doctrines as heuristic functions and settlement as shortcut.'),
    ('Body Text', '6. An empirical calibration pipeline (LaBSE + linear probes + Mahalanobis weights) that makes the judicial complex constructible from existing data.'),
    ('Body Text', ''),
]
